# BambuLab plugin path. Uncomment only ONE line for your CPU architecture.
# amd64 (x86_64)
# Plugins.BambuLab.System.Path=/usr/libexec/zabbix/zabbix_agent2_plugin_bambulab_linux_amd64
# arm64 (aarch64)
# Plugins.BambuLab.System.Path=/usr/libexec/zabbix/zabbix_agent2_plugin_bambulab_linux_arm64